services:
  - type: web
    name: sentao-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000 