services:
  - type: web
    name: sentao-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 